#!/bin/sh

set -e

ALL_OPTIONS=$*

PROGRAM=$0
VERSION=0.8.0

DATABASE=wdb
USERNAME=
HOSTNAME=
PORT=

AUTOMATIC_STATIONS=true

version()
{
	echo $PROGRAM $VERSION
}

help()
{
		echo "Load several locations from api.met.no/locationforecast into a wdb database

This is a wrapper script for locationForecastLoad. It calls that program for 
all norwegian stations with a wmo number in the wdb database. Likewise, it 
calls locationforecastLoad for all stations mentioned in a file. By default,
the file $EXTRA_STATIONS will be loaded

Options:

  -d [ --database ] arg (=wdb) Database name (ex. wdb)
  -h [ --host ] arg            Database host (ex. somehost.met.no)
  -u [ --user ] arg            Database user name
  -p [ --port ] arg            Database port number to connect to

  --no-automatic-stations      Skip loading of stations based on any algorithm
  --load-file arg                Load stations from the given file instead of 
                               the default file
"	
}

wdb_arguments()
{
	[ -z $DATABASE ] || echo -n "-d$DATABASE "
	[ -z $HOSTNAME ] || echo -n "-h$HOSTNAME "
	[ -z $USERNAME ] || echo -n "-u$USERNAME "
	[ -z $PORT ] || echo -n "-p$PORT "
}

TEMP=`getopt -o d:h:u:U:p: --long version,help,database:,host:,username:,port:,no-automatic-stations,load-file: -n $1 -- "$@"`
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
eval set -- "$TEMP"


while true; do 
	case "$1" in
		--version)
			version
			exit 0
			;;
		--help) 
			help
			exit 0
			;;
		-d|--database)
			DATABASE="$2"
			shift 2
			;;
		-h|--host)
			HOSTNAME="$2"
			shift 2
			;;
		-u|-U|--username)
			USERNAME="$2"
			shift 2
			;;
		-p|--port)
			PORT=$2
			shift 2
			;;
		--no-automatic-stations)
			AUTOMATIC_STATIONS=false
			shift
			;;
		--load-file)
			shift 2
			;;			
		--)
			shift
			break
			;;
		*)
			# this should never happen
			echo invalid argument: $1
			exit 1
			;;
	esac
done

LOAD="locationforecastLoad --list"
FASTLOAD="wdb-fastload `wdb_arguments`" 

LOAD_FILE=/home/wdb/parch_locationforecastload.$PPID.`date +%Y%m%d%H`

for URL in `parch_stationlist $ALL_OPTIONS --url`; do
	$LOAD $URL >> $LOAD_FILE
	sleep 0.25
done

$FASTLOAD $LOAD_FILE && rm $LOAD_FILE
