#!/bin/sh

set -e

PROGRAM=$0
VERSION=0.2.0

DATABASE=wdb
USERNAME=
HOSTNAME=
PORT=

AUTOMATIC_STATIONS=true

#SQLDIR=.
#CONFDIR=.
SQLDIR=/usr/share/parch_locationforecastLoad
CONFDIR=/etc/parch_locationforecastLoad

EXTRA_STATIONS=$CONFDIR/foreign_stations.dat

version()
{
	echo $PROGRAM $VERSION
}

help()
{
		echo "Load several locations from api.met.no/locationforecast into a wdb database

This is a wrapper script for locationForecastLoad. It calls that program for 
all norwegian stations with a wmo number in the wdb database. Likewise, it 
calls locationforecastLoad for all stations mentioned in a file. By default,
the file $EXTRA_STATIONS will be loaded

Options:

  -d [ --database ] arg (=wdb) Database name (ex. wdb)
  -h [ --host ] arg            Database host (ex. somehost.met.no)
  -u [ --user ] arg            Database user name
  -p [ --port ] arg            Database port number to connect to

  --no-automatic-stations      Skip loading of stations based on any algorithm
  --load-file arg                Load stations from the given file instead of 
                               the default file
"	
}

psql_arguments()
{
	[ -z $DATABASE ] || echo -n "-d$DATABASE "
	[ -z $HOSTNAME ] || echo -n "-h$HOSTNAME "
	[ -z $USERNAME ] || echo -n "-U$USERNAME "
	[ -z $PORT ] || echo -n "-p$PORT "
}

wdb_arguments()
{
	[ -z $DATABASE ] || echo -n "-d$DATABASE "
	[ -z $HOSTNAME ] || echo -n "-h$HOSTNAME "
	[ -z $USERNAME ] || echo -n "-u$USERNAME "
	[ -z $PORT ] || echo -n "-p$PORT "
}

TEMP=`getopt -o d:h:u:U:p: --long version,help,database:,host:,username:,port:,no-automatic-stations,load-file: -n $1 -- "$@"`
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
eval set -- "$TEMP"


while true; do 
	case "$1" in
		--version)
			version
			exit 0
			;;
		--help) 
			help
			exit 0
			;;
		-d|--database)
			DATABASE="$2"
			shift 2
			;;
		-h|--host)
			HOSTNAME="$2"
			shift 2
			;;
		-u|-U|--username)
			USERNAME="$2"
			shift 2
			;;
		-p|--port)
			PORT=$2
			shift 2
			;;
		--no-automatic-stations)
			AUTOMATIC_STATIONS=false
			shift
			;;
		--load-file)
			EXTRA_STATIONS=$2
			shift 2
			;;			
		--)
			shift
			break
			;;
		*)
			# this should never happen
			echo invalid argument: $1
			exit 1
			;;
	esac
done


PSQL="psql -At `psql_arguments`"
LOAD="locationforecastLoad `wdb_arguments`"



if [ true = "$AUTOMATIC_STATIONS" ]; then
	$PSQL < $SQLDIR/create_norwegian_load_list.sql | grep -v SELECT | xargs $LOAD
fi

for FILE in $EXTRA_STATIONS; do
	ABSOLUTE_PATH=`readlink -f $FILE`
	echo $ABSOLUTE_PATH
	sed s,__STATIONS_LIST__,/$ABSOLUTE_PATH,g $SQLDIR/create_foreign_load_list.sql | $PSQL | grep ^[0-9] | xargs $LOAD
done
