#!/bin/sh

set -e

ALL_OPTIONS=$*

PROGRAM=$0
VERSION=0.8.0

DATABASE=wdb
USERNAME=
HOSTNAME=
PORT=

AUTOMATIC_STATIONS=true

#BINDIR=.
#CONFDIR=.
BINDIR=/usr/bin/
CONFDIR=/etc/parch-util

version()
{
	echo $PROGRAM $VERSION
}

help()
{
		echo "Load several locations from api.met.no/locationforecast into a wdb database

This is a wrapper script for locationForecastLoad. It calls that program for 
all norwegian stations with a wmo number in the wdb database. Likewise, it 
calls locationforecastLoad for all stations mentioned in a file. By default,
the file $EXTRA_STATIONS will be loaded

Options:

  -d [ --database ] arg (=wdb) Database name (ex. wdb)
  -h [ --host ] arg            Database host (ex. somehost.met.no)
  -u [ --user ] arg            Database user name
  -p [ --port ] arg            Database port number to connect to

  --no-automatic-stations      Skip loading of stations based on any algorithm
  --load-file arg                Load stations from the given file instead of 
                               the default file
"	
}

wdb_arguments()
{
	[ -z $DATABASE ] || echo -n "-d$DATABASE "
	[ -z $HOSTNAME ] || echo -n "-h$HOSTNAME "
	[ -z $USERNAME ] || echo -n "-u$USERNAME "
	[ -z $PORT ] || echo -n "-p$PORT "
}

TEMP=`getopt -o d:h:u:U:p: --long version,help,database:,host:,username:,port:,no-automatic-stations,load-file: -n $1 -- "$@"`
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
eval set -- "$TEMP"


while true; do 
	case "$1" in
		--version)
			version
			exit 0
			;;
		--help) 
			help
			exit 0
			;;
		-d|--database)
			DATABASE="$2"
			shift 2
			;;
		-h|--host)
			HOSTNAME="$2"
			shift 2
			;;
		-u|-U|--username)
			USERNAME="$2"
			shift 2
			;;
		-p|--port)
			PORT=$2
			shift 2
			;;
		--no-automatic-stations)
			AUTOMATIC_STATIONS=false
			shift
			;;
		--load-file)
			shift 2
			;;			
		--)
			shift
			break
			;;
		*)
			# this should never happen
			echo invalid argument: $1
			exit 1
			;;
	esac
done


CREATE_LOAD_DATA="locationforecastLoad `wdb_arguments` --namespace=88,456,88 --list"
LOAD="wdb-fastload --namespace=88,456,88 `wdb_arguments`"

#$BINDIR/parch_stationlist $ALL_OPTIONS --placenamespace=456 | xargs -r $CREATE_LOAD_DATA | $LOAD

for STATION in `$BINDIR/parch_stationlist $ALL_OPTIONS --placenamespace=456`; do
     $CREATE_LOAD_DATA $STATION | $LOAD || true
done